{
    "openapi": "3.0.3",
    "info": {
        "title": "Course RESTful API",
        "description": "This is how we learn about OpenAPI",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "https://{environment}.vps.com/api/v1",
            "variables": {
                "environment": {
                    "default": "dev",
                    "enum": [
                        "dev",
                        "qa",
                        "prod"
                    ]
                }
            }
        }
    ],
    "externalDocs": {
        "url": "https://www.youtube.com/c/ProgrammerZamanNow",
        "description": "Youtube Programmer Zaman Now"
    },
    "paths": {
        "/todolist": {
            "get": {
                "tags": ["Todolist"],
                "summary": "Get all todolist",
                "description": "Get all active todolist by default",
                "security": [
                    {"TodolistAuth": []}
                ],
                "parameters": [
                    {
                        "name": "include_done",
                        "in": "query",
                        "required": false,
                        "description": "Include done todolist",
                        "schema": {
                            "type": "boolean",
                            "default": true,
                            "nullable": true
                        }
                    },
                    {
                        "name": "name",
                        "in": "query",
                        "required": false,
                        "description": "Filter todolist by name",
                        "schema": {
                            "type": "string",
                            "nullable": true,
                            "minLength": 1,
                            "maxLength": 100
                        },
                        "examples": {
                            "java": {
                                "value": "Java"
                            },
                            "php": {
                                "value": "PHP"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success get all todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ArrayTodolist"
                                },
                                "examples": {
                                    "success": {
                                        "description": "Example success get all todolist",
                                        "value": [
                                            {
                                                "id": "1",
                                                "name": "Java",
                                                "priority": 3,
                                                "tags": [
                                                    "Java",
                                                    "Programming"
                                                ]
                                            },
                                            {
                                                "id": "2",
                                                "name": "PHP",
                                                "priority": 2,
                                                "tags": [
                                                    "PHP",
                                                    "Programming"
                                                ]
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": ["Todolist"],
                "summary": "Create todolist",
                "description": "Create new todolist to database",
                "security": [
                    {"TodolistAuth": []}
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateOrUpdateTodolist"
                            },
                            "examples": {
                                "java": {
                                    "description": "Example create todolist Java",
                                    "value": {
                                        "name": "Java",
                                        "priority": 3,
                                        "tags": [
                                            "JAVA", "Programming"
                                        ]
                                    }
                                },
                                "php": {
                                    "description": "Example create todolist PHP",
                                    "value": {
                                        "name": "PHP",
                                        "priority": 3,
                                        "tags": [
                                            "PHP", "Programming"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Success create todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Todolist"
                                },
                                "examples": {
                                    "java": {
                                        "description": "Success create java todolist",
                                        "value": {
                                            "id": "1",
                                            "name": "Java",
                                            "priority": 3,
                                            "tags": [
                                                "Java",
                                                "Programming"
                                            ]
                                        }
                                    },
                                    "php": {
                                        "description": "Success create PHP todolist",
                                        "value": {
                                            "id": "1",
                                            "name": "PHP",
                                            "priority": 3,
                                            "tags": [
                                                "PHP",
                                                "Programming"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/todolist/{todolistId}": {
            "put": {
                "tags": ["Todolist"],
                "summary": "Update existing todolist",
                "description": "Update existing todolist in database",
                "security": [
                    {"TodolistAuth": []}
                ],
                "parameters": [
                    {
                        "name": "todolistId",
                        "in": "path",
                        "required": true,
                        "description": "Todolist id for updated",
                        "schema": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 100
                        }
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateOrUpdateTodolist"
                            },
                            "examples": {
                                "java": {
                                    "description": "Example create todolist Java",
                                    "value": {
                                        "name": "Java",
                                        "priority": 3,
                                        "tags": [
                                            "JAVA", "Programming"
                                        ]
                                    }
                                },
                                "php": {
                                    "description": "Example create todolist PHP",
                                    "value": {
                                        "name": "PHP",
                                        "priority": 3,
                                        "tags": [
                                            "PHP", "Programming"
                                        ]
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success update todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Todolist"
                                },
                                "examples": {
                                    "java": {
                                        "description": "Success update java todolist",
                                        "value": {
                                            "id": "1",
                                            "name": "Java",
                                            "priority": 3,
                                            "tags": [
                                                "Java",
                                                "Programming"
                                            ]
                                        }
                                    },
                                    "php": {
                                        "description": "Success update PHP todolist",
                                        "value": {
                                            "id": "1",
                                            "name": "PHP",
                                            "priority": 3,
                                            "tags": [
                                                "PHP",
                                                "Programming"
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": ["Todolist"],
                "summary": "Delete existing todolist",
                "description": "Delete existing todolist in database",
                "security": [
                    {"TodolistAuth": []}
                ],
                "parameters": [
                    {
                        "name": "todolistId",
                        "in": "path",
                        "required": true,
                        "description": "Todolist id for deleted",
                        "schema": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 100
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success delete todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "success": {
                                        "description": "Success delete todolist",
                                        "value": {
                                            "success": true
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Failed delete todolist",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "success": {
                                            "type": "boolean"
                                        }
                                    }
                                },
                                "examples": {
                                    "failed": {
                                        "description": "Failed delete todolist",
                                        "value": {
                                            "success": false
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "TodolistAuth": {
                "description": "Auth for todolist RESTfull API",
                "type": "apiKey",
                "in": "header",
                "name": "X-API-Key"
            }
        },
        "schemas": {
            "Todolist": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "priority": {
                        "type": "number",
                        "format": "int32"
                    },
                    "tags": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "CreateOrUpdateTodolist": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "required": true,
                        "minLength": 1
                    },
                    "priority": {
                        "type": "integer",
                        "format": "int32",
                        "required": true,
                        "default": 1
                    },
                    "tags": {
                        "type": "array",
                        "required": false,
                        "minItems": 1,
                        "items": {
                            "type": "string",
                            "minLength": 1
                        }
                    }
                }
            },
            "ArrayTodolist": {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/Todolist"
                }
            }
        }
    }
}
